apiVersion: v1
kind: Template
metadata:
  name: alert-translator
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: alert-translator
- apiVersion: v1
  kind: Service
  metadata:
    name: alert-translator-${GCHAT_SPACE}
  spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: ${PORT}
    selector:
      app: alert-translator-${GCHAT_SPACE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: alert-translator
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "alert-translator design does not adequately account for multiple replicas"
    name: alert-translator-${GCHAT_SPACE}
  spec:
    replicas: ${{REPLICAS}}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: alert-translator-${GCHAT_SPACE}
    template:
      metadata:
        labels:
          app: alert-translator-${GCHAT_SPACE}
      spec:
        serviceAccountName: alert-translator
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: alert-translator
          env:
          - name: PORT
            value: ${PORT}
          - name: PROVIDER
            value: ${PROVIDER}
          - name: WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: alert-translator-${GCHAT_SPACE}
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
parameters:
- name: IMAGE
  value: quay.io/app-sre/alert-translator
  displayName: alert-translator image
  description: alert-translator docker image. Defaults to quay.io/app-sre/alert-translator
- name: IMAGE_TAG
  value: latest
  displayName: alert-translator version
  description: alert-translator version which defaults to latest
- name: PORT
  value: '8080'
- name: WEBHOOK_URL
  value: ''
- name: PROVIDER
  value: 'googlechat'
- name: GCHAT_SPACE
  value: ''
- name: REPLICAS
  value: '1'
- name: MEMORY_REQUESTS
  value: 100Mi
- name: MEMORY_LIMIT
  value: 100Mi
- name: CPU_REQUESTS
  value: 50m
- name: CPU_LIMIT
  value: 100m
